name: Production Deployment

on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          your-dockerhub-username/sports-api:latest
          your-dockerhub-username/sports-api:${{ github.sha }}

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /sports-api
          docker compose pull
          docker compose up -d
          docker system prune -f